name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 🔊 Upload code coverage to GitHub Artifacts (for SonarCloud)
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/lcov.info
